##############################################
#           SkinsRestorer Config             #
#            Made By Th3Tr0LLeR              #
##############################################



#Should SkinsRestorer check for updates ?
UpdateCheck: true

#You can enable that if you're using AutoIn.
UseAutoInSkins: false

#This can be enabled if you are experiencing bot attacks.
UseBotFeature: false

#This is for preventing skin change spam.
SkinChangeCooldown: 30

#Mojang has a limit for getting skins.
#This website uses proxies to get the skin data
#From mojang, so you will not be limited.
#However. If you do not trust mcapi.ca, you can disable that option.
MCAPI:
  Enabled: true
  GetSkinProfileURL: https://mcapi.ca/name/uuid/{uuid}

#A list of disabled skins. A permision will be needed for them.
DisabledSkins:
  - SomeSkin
  - AnotherSkin

#If this is enabled and configured SkinsRestorer will keep the skins
#in a MySQL database. This is using less performance.
MySQL:
  Enabled: false
  Host: localhost
  Port: 3306
  Database: db
  SkinTable: Skins
  PlayerTable: Players
  Username: root
  Password: pass

#Turn this to true if you want to disable
#The /skin command.
DisableSkinCommand: false