#This option disables automatic requesting & applying skins on join
#Commands still work
DisableOnJoinSkins: false

#This is for preventing skin change spam
SkinChangeCooldown: 30

# Mojang API (Used to get our skin data) has request limit:
# You can only request skin data of the same player only once in 10 minutes
# 
# To bypass this, here are some our default alternative APIs to get the skin data
# Feel free to change them to your own
Alternatives:
  SkinPropertyURL: https://mcapi.ca/name/uuid/
  UUIDURL: https://us.mc-api.net/v3/uuid/
  
DefaultSkin:
  Enabled:
  Names:

# MySQL database for large servers
# or just to boost the performance
MySQL:
  Enabled: false
  Host: localhost
  Port: 3306
  Database: db
  SkinTable: Skins
  PlayerTable: Players
  Username: root
  Password: pass