name: SkinsRestorer
main: skinsrestorer.bukkit.SkinsRestorer
<<<<<<< HEAD
version: 12.5
=======
version: 12.4.2
>>>>>>> origin/master
author: Blackfire62,Th3Tr0LLeR
commands:
  skinsrestorer:
    aliases: [sr]
    description: Admin commands.
  skin:
    description: Sets your skin.