name: SkinsRestorer
main: skinsrestorer.bukkit.SkinsRestorer
version: 13.0.0
authors: [Blackfire62, Th3Tr0LLeR]
softdepend: [Multiverse-Core]
commands:
  skinsrestorer:
    aliases: [sr]
    description: Admin commands.
  skin:
    description: Sets your skin.
  skinver:
    description: Shows the SR version