name: SkinsRestorer
main: skinsrestorer.bukkit.SkinsRestorer
version: 12.1 (Blackfire62's fork)
author: Blackfire62,Th3Tr0LLeR
load: STARTUP
commands:
  skinsrestorer:
    aliases: [sr]
    description: Admin commands.
  skin:
    description: Sets your skin.