name: SkinsRestorer
main: skinsrestorer.bukkit.SkinsRestorer
version: 12.6
author: Blackfire62,Th3Tr0LLeR
commands:
  skinsrestorer:
    aliases: [sr]
    description: Admin commands.
  skin:
    description: Sets your skin.
  clearskin:
    description: Removes your skin.