##############################
#  SkinsRestorer Config.yml  #
#  Generated on 13.6         #
##############################
#
# We from SRTeam thank you for using our plugin!
# If you are confused or need help chek out the wiki: https://github.com/SkinsRestorer/SkinsRestorerX/wiki/
# not working or get error?? -> Discord: https://discord.me/SkinsRestorer/

# If true, players can change skins without permission.
SkinWithoutPerm: true

# How long are the skins stored in database (in minutes)
SkinExpiresAfter: 1584

# Timeout for changing skins (set to 0 to disable)
SkinChangeCooldown: 30

# Set the language you will use - Files are located in /SkinsRestorer/languages directory
# You can add custom locale file by copying the english.yml, renaming the new file into your language and editing it
# Default: english - english.yml
Locale: english

# The new Permissions System information can be foud on our wiki here:
# https://github.com/SkinsRestorer/SkinsRestorerX/wiki/cmds-&-perms
Permissions:
  NewPermissions: true
  
# Allows the usage of per skin perm. example: skinsrestorer.skin.notch OR skinsrestorer.skin.xknat
# !~ requires  NewPermissions: true 
PerSkinPermissions: false

# Enable or disable default skins
# If there is more than one, the plugin will choose a random one.
DefaultSkins:
  Enabled: false
  ApplyForPremium: false
  Names:
    - xknat

# Skins in this list will be disabled, so users can't set t
DisabledSkins:
  Enabled: false
  Names:
    - Steve
    - Owner

# Multi-Bungee support
# Enable this if you have issues with skins in multi-proxy environments
# If your using bungee and you have the plugin in all spigot servers and it still does not work, turn this on.
# (This is automatically enabled if you have RedisBungee)
MultiBungee:
  Enabled: false

# Settings for MySQL skin storage (recommended for big BungeeCord networks)
# !~ IF YOU USE BUNGEE, DO NOT mysql Spigot ~!
MySQL:
  Enabled: false
  Host: localhost
  Port: 3306
  Database: db
  Username: root
  Password: pass
  SkinTable: 'Skins'
  PlayerTable: 'Players'

# Enable or disable the updater.
Updater:
  Enabled: true

# Stop the process of setting a skin if the LoginEvent was canceled by an AntiBot plugin
NoSkinIfLoginCanceled: true

#end 

# Usefull Links #
# Website: https://skinsrestorer.net/
# Wiki https://github.com/SkinsRestorer/SkinsRestorerX/wiki/
# spigot: https://www.spigotmc.org/resources/skinsrestorer.2124/
# github: https://github.com/SkinsRestorer/SkinsRestorerX/
# discord: https://discord.me/SkinsRestorer/
