##############################
#  SkinsRestorer Config.yml  #
##############################

# enables /skin without permissions
SkinWithoutPerm: false

# How long are the skins stored in database (in minutes)
SkinExpiresAfter: 5

# Timeout for skin changing (set to 0 to disable)
SkinChangeCooldown: 30
 
# Enable or disable default skins
# If there is more than one, the plugin will choose a random one.
DefaultSkins:
  Enabled: false
  Names:
    - Steve
    
#Disable skin names
#Put skins you want to disable on the list
#Player wont be able to set these skins
#[skinsrestorer.bypassdisabled bypasses this]
DisabledSkins:
  Enabled: false
  Names:
    - Steve
    
# Multi-Bungee support
# Enable this if you have issues with skins in multi-proxy environments
# (This is automatically enabled if you have RedisBungee)
MultiBungee:
  Enabled: false

# Settings for MySQL skin storage (recommended for big BungeeCord networks)
MySQL:
  Enabled: false
  Host: localhost
  Port: 3306
  Database: db
  SkinTable: Skins
  PlayerTable: Players
  Username: root
  Password: pass

# Enable or disable the updater.
Updater:
  Enabled: true