name: SkinsRestorer
main: skinsrestorer.bukkit.SkinsRestorer
version: ${project.version}
description: Ability to restore/change skins on servers!
authors: [Th3Tr0LLeR]
softdepend: [Multiverse-Core]
commands:
  skinsrestorer:
    aliases: [sr]
    description: Admin commands.
  skin:
    description: Main command.
  skins:
    description: Opens skins GUI
permissions:
   skinsrestorer.playercmds:
     description: Allows access to all main commands.
   skinsrestorer.playercmds.menu:
     description: Allows access to the /skins menu
   skinsrestorer.cmds:
     description: Allows access to administrative commands.
   skinsrestorer.bypassdisabled:
     description: Allows access to disabled skins.
   skinsrestorer.bypasscooldown:
     description: Bypasses the skin change cooldown (if any).