name: SkinsRestorer
main: skinsrestorer.bukkit.SkinsRestorer
version: 13.2-SNAPSHOT
description: Ability to restore/change skins on servers! (Offline and Online Mode). (Bungee/Bukkit/Sponge)
authors: [Th3Tr0LLeR]
softdepend: [Multiverse-Core]
commands:
  skinsrestorer:
    aliases: [sr]
    description: Admin commands.
  skin:
    description: Main command.
  skins:
    description: Opens skins GUI
permissions:
   skinsrestorer.playercmds:
     description: Allows access to all main commands.
     default: op
   skinsrestorer.cmds:
     description: Allows access to administrative commands.
     default: op
