name: SkinsRestorer
main: skinsrestorer.bukkit.SkinsRestorer
version: 10.5.6
author: Th3Tr0LLeR
load: startup
softdepend: [AutoIn]
commands:
  skinsrestorer:
    aliases: [sr]
    description: SkinsRestorer's main command.
  skin:
    description: Use this command to change your skin.